//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNTC.Finansoft.Accounting.DTO.Fichas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("apo.Configuracion")]
    public partial class Configuracion1
    {    
        public int id { get; set; }
        public string nombre { get; set; }
        public string idCuenta { get; set; }
        public Nullable<int> multiplicador { get; set; }
        public string saldoMinimo { get; set; }

        [ForeignKey("TiposCalculo")]
        public Nullable<int> idTipoCuotaCalculo { get; set; }

        public string porcentaje { get; set; }
        public string valor { get; set; }
        public string porcentajeCuota { get; set; }
        public string valorCuota { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public long RangoDesde { get; set; }
        public long RangoHasta { get; set; }
        public long ConsecutivoActual { get; set; }

        public virtual TiposCalculo TiposCalculo { get; set; }
        public virtual ICollection<FichasAportes> FichasAportes { get; set; }
    }
}
