//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNTC.Finansoft.Accounting.DTO.Fichas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("aho.Configuracion")]
    public partial class Configuracion
    {

        public static int IdTipoCuotaCalculo { get; set; }
        public int id { get; set; }
        [ForeignKey("TiposFichas")]
        public string tipoAhorro { get; set; }
        public Nullable<int> cuentaContable { get; set; }
        public string nombre { get; set; }
        public string porcentajeParaAhorros { get; set; }
        public string tasaEfectiva { get; set; }
        public string multiplicador { get; set; }
        public string peridoLiquidacionMinima { get; set; }
        public string valorMinimo { get; set; }
        public string valorMaximo { get; set; }
        public string diasGracia { get; set; }
        public string periodoGraciaRenovable { get; set; }
        public string periodoInactividadMinima { get; set; }
        public string cuotasMorosasLiquidacionTitulo { get; set; }
        public string modalidad { get; set; }
        public string tipoRetencion { get; set; }
        public string fuenteContable { get; set; }
        public string cuentaRetencion { get; set; }
        public string cuentaGastoInteres { get; set; }
        public string cuentaCausacion { get; set; }
        public string cuentaCortoPlazo { get; set; }
        public string cuentaIngresos { get; set; }
        public string cuentaLargoPlazoActiva { get; set; }
        public string cuentaCortoPlazoInactiva { get; set; }
        public string cuentaLargoPlazoInactiva { get; set; }
        public string cuentaMayor6Menor12 { get; set; }
        public string cuentaMayor12Menor18 { get; set; }
        public string cuentaMayor18 { get; set; }
        public Nullable<bool> generaInteresCausacion { get; set; }
        public Nullable<bool> permiteConsignacionSaldo { get; set; }
        public Nullable<bool> reconoceInteres { get; set; }
        public Nullable<bool> permiteAsociadoDiferente { get; set; }
        public Nullable<bool> permiteCambiarFechaCreacion { get; set; }
        public Nullable<bool> liquidaInteresEstadoInactivo { get; set; }
        public Nullable<bool> capitalizaInteresLineaAhorros { get; set; }
        public Nullable<int> idActa { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public long RangoDesde { get; set; }
        public long RangoHasta { get; set; }
        public long ConsecutivoActual { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        
        public virtual TiposFichas TiposFichas { get; set; }
        public virtual ICollection<FichasAhorros> FichasAhorros { get; set; }
    }
}
