//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNTC.Finansoft.Accounting.DTO.Fichas
{
    using FNTC.Finansoft.Accounting.DTO.Terceros;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "apo.FichasAportes")]
    public class FichasAportes
    {
        public int id { get; set; }
        public string numeroCuenta { get; set; }
        [ForeignKey("Configuracion1")]
        public Nullable<int> idConfiguracion { get; set; }
        [ForeignKey("Terceros")]
        public string idPersona { get; set; }
        public string tipoPago { get; set; }
        public string porcentaje { get; set; }
        public string valor { get; set; }
        public string valorCuota { get; set; }
        public string totalAportes { get; set; }
        public Nullable<System.DateTime> fechaApertura { get; set; }
        public Nullable<bool> activa { get; set; }
        public string asesor { get; set; }


        public virtual Configuracion1 Configuracion1 { get; set; }
        public virtual Tercero Terceros { get; set; }

    }
}
