//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNTC.Finansoft.Accounting.DTO.Fichas
{
    using FNTC.Finansoft.Accounting.DTO.Terceros;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "aho.FichasAhorros")]
    public class FichasAhorros
    {
        public int id { get; set; }
        [ForeignKey("TiposFichas")]
        public string tipoFicha { get; set; }
        [ForeignKey("Configuracion")]
        public Nullable<int> idConfiguracion { get; set; }
        public string numeroCuenta { get; set; }
        [ForeignKey("Terceros")]
        public string idPersona { get; set; }
        public string tipoPago { get; set; }
        public string porcentaje { get; set; }
        public string valor { get; set; }
        public string valorCuota { get; set; }
        public string totalAhorros { get; set; }
        [ForeignKey("TiposCalculo")]
        public Nullable<int> tipoCalculoCuota { get; set; }
        public string CDAT { get; set; }
        public string idBeneficiario1 { get; set; }
        public string idBeneficiario2 { get; set; }
        public string tipoDevolucion { get; set; }
        public string valorTitulo { get; set; }
        public string plazo { get; set; }
        public Nullable<bool> tituloPignorado { get; set; }
        public Nullable<bool> capitalizaInteres { get; set; }
        public Nullable<int> idLineaDeposito { get; set; }
        public string contractual { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fechaApertura { get; set; }
        public string empresa { get; set; }
        public virtual Configuracion Configuracion { get; set; }
        public virtual TiposCalculo TiposCalculo { get; set; }
        public virtual TiposFichas TiposFichas { get; set; }
        public virtual Tercero Terceros { get; set; }
        //Añadidos Tabla
        [RegularExpression(@"^(\d{1}\.)?(\d+\.?)+(,\d{2})?$", ErrorMessage = "Solo números")]
        public decimal Tasa_interes { get; set; }
        [RegularExpression(@"^\d+$", ErrorMessage = "Solo números")]
        public int? Plazo_meses { get; set; }
        public DateTime? Fecha_Vencimiento { get; set; }

    }
}
