//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNTC.Finansoft.Accounting.DTO.Fichas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("apo.TiposCalculo")]
    public partial class TiposCalculo
    {    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<FichasAhorros> FichasAhorros { get; set; }
        public virtual ICollection<Configuracion1> Configuracion1 { get; set; }

        public static explicit operator TiposCalculo(int v)
        {
            throw new NotImplementedException();
        }
    }
}
