//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNTC.Finansoft.Accounting.DTO.FormularioVinculacion
{
    using FNTC.Finansoft.Accounting.DTO.Terceros;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("dbo.formatoVinculacion")]
    public partial class formatoVinculacion
    {
        [Key]
        public int id { get; set; }

        [Required]
        public string ciudadsolicitud { get; set; }

        
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechasolicitud { get; set; }

        [Required]
        public string registrosolicitud { get; set; }
        public string asesorcomercial { get; set; }

        [Required]
        [ForeignKey("TerceroFK")]
        public string cedulaaso { get; set; }
        
        public int personascargo { get; set; }
        public int estratoresidencia { get; set; }
        public string nivelestudio { get; set; }
        
        
        public string nombreconyugue { get; set; }
        public string cedulaconyuge { get; set; }
        public string celularconyugue { get; set; }
        public string ocupacionconyugue { get; set; }
        public string empresaconyugue { get; set; }
        public string telefonoconyugue { get; set; }
        public string nombre1 { get; set; }
        public string documento1 { get; set; }
        public string parentesco1 { get; set; }
        public string sexo1 { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechanacimiento1 { get; set; }
        public string porcentaje1 { get; set; }
        public string edad1 { get; set; }
        public string nombre2 { get; set; }
        public string documento2 { get; set; }
        public string parentesco2 { get; set; }
        public string sexo2 { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechanacimiento2 { get; set; }
        public string porcentaje2 { get; set; }
        public string edad2 { get; set; }
        public string nombre3 { get; set; }
        public string documento3 { get; set; }
        public string parentesco3 { get; set; }
        public string sexo3 { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechanacimiento3 { get; set; }
        public string porcentaje3 { get; set; }
        public string edad3 { get; set; }
        public string nombre4 { get; set; }
        public string documento4 { get; set; }
        public string parentesco4 { get; set; }
        public string sexo4 { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechanacimiento4 { get; set; }
        public string porcentaje4 { get; set; }
        public string edad4 { get; set; }
        public string nombre5 { get; set; }
        public string documento5 { get; set; }
        public string parentesco5 { get; set; }
        public string sexo5 { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechanacimiento5 { get; set; }
        public string porcentaje5 { get; set; }
        public string edad5 { get; set; }
        public string nombre6 { get; set; }
        public string documento6 { get; set; }
        public string parentesco6 { get; set; }
        public string sexo6 { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechanacimiento6 { get; set; }
        public string porcentaje6 { get; set; }
        public string edad6 { get; set; }

        [Required]
        public string entidadlabora { get; set; }

        //[DataType(DataType.Date)]
        public string fechavinculacion { get; set; }
        public string tipocontrato { get; set; }
        public string oficina { get; set; }
        public string codigo { get; set; }
        public string direccionabora { get; set; }
        public string telefonolabora { get; set; }
        public string extencionlabora { get; set; }
        public string cargolabora { get; set; }
        public string actividadeconomica { get; set; }
        public string CIIU { get; set; }
        public string sueldobasico { get; set; }
        public string correolabora { get; set; }
        public string cesantiaslabora { get; set; }
        public string adminrecursospublicos { get; set; }
        public string ingresobasico { get; set; }
        public string otrosingresos { get; set; }
        public string totalingresos { get; set; }
        public string gastosmensuales { get; set; }
        public string descotrosingresos { get; set; }
        public string totalactivos { get; set; }
        public string totalpasivos { get; set; }
        public string bancarias { get; set; }
        public string bancarias1 { get; set; }
        public string entidadesfinancieras { get; set; }
        public string entidadesfinancieras1 { get; set; }
        public string otrosegresos { get; set; }
        public string otrosegresos1 { get; set; }
        public string descotrosegresos { get; set; }
        public string cuentasexterior { get; set; }
        public string entidadexterior { get; set; }
        public string tipomoneda { get; set; }
        public string cuentaexterior { get; set; }
        public string ciudadexterior { get; set; }
        public string paisexterior { get; set; }
        public string monedaextranjera { get; set; }
        public string importacion { get; set; }
        public string exportacion { get; set; }
        public string inversiones { get; set; }
        public string prestamos { get; set; }
        public string otroextranjera { get; set; }

        [Required]
        public string aportemensual { get; set; }
        public string variaraporte { get; set; }
        public string dia { get; set; }
        public string mes { get; set; }
        public string ano { get; set; }
        public string tipo { get; set; }


        public virtual Tercero TerceroFK { get; set; }
    }
}
