//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNTC.Finansoft.Accounting.DAL.FabricaCreditosDal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_finantecFabricaCreditosEntities : DbContext
    {
        public BD_finantecFabricaCreditosEntities()
            : base("name=BD_finantecFabricaCreditosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ReferenciasCodeudor> ReferenciasCodeudor { get; set; }
        public virtual DbSet<ReferenciasPorSolicitud> ReferenciasPorSolicitud { get; set; }
    }
}
