//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNTC.Finansoft.Accounting.DAL.FabricaCreditosDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciasCodeudor
    {
        public string nit { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string genero { get; set; }
        public string fechaNacimiento { get; set; }
        public string telefono { get; set; }
        public string telefonoMovil { get; set; }
        public string correoElectronico { get; set; }
        public Nullable<bool> esAsociado { get; set; }
        public Nullable<bool> esReferencia { get; set; }
        public Nullable<bool> esEmpleado { get; set; }
        public Nullable<bool> idActividad { get; set; }
        public string idPadre { get; set; }
        public string direccionResidencia { get; set; }
        public Nullable<bool> esCodeudor { get; set; }
    }
}
