//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNTC.Finansoft.Accounting.DAL.FabricaCreditosDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciasPorSolicitud
    {
        public string idReferencia { get; set; }
        public string idSolicitud { get; set; }
        public string nomEmpresa { get; set; }
        public string telEmpresa { get; set; }
        public string parentesco { get; set; }
        public Nullable<bool> verificada { get; set; }
        public string comentarios { get; set; }
    }
}
