// <auto-generated />
namespace FNTC.Finansoft.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cuentadeterioro5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cuentadeterioro5));
        
        string IMigrationMetadata.Id
        {
            get { return "202107232047260_cuentadeterioro5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
